### PR TITLE
validate directory path

### LINKED ISSUE #606: A non indicative error in CLI v.0.9.50 for parameter Directory
Description:
Entering command into the CLI that contains a directory which doesn't exists will cause for a non indicative error.

Steps to reproduce:
1. Write a command in the CLI that contains a directory which does not exists :in this example I wrote the directories-  /content/content 
```
cslang>run --f C:/Users/finkelm/Desktop/tutorials/hiring/new_hire.sl --cp C:/Use
rs/finkelm/Desktop/tutorials,C:/Users/finkelm/Desktop/cslang# /content/content/io/
cloudslang/base --i first_name=john,last_name=doe --spf C:/Users/finkelm/Desktop
/tutorials/properties/bcompany.prop.sl
```
Actual result:
I got this error massage that didn't tell me what directory is the problematic one.

```
Command failed java.lang.IllegalArgumentException: Parameter 'directory' is not
a directory
```
Expected result:
I expect to get an error that tells me which directory the error is talking about.

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #606 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

**Comment by Bonczidai** [comment]
@milanafinkel @SamMarkowitz now the error message contains the dir name: `Command failed java.lang.IllegalArgumentException: Parameter 'C:\a\b\c' is not a directory` -- how do you like it?

**Comment by SamMarkowitz** [comment]
Does the trick for me.

**Comment by mihaitusa** [comment]
@Bonczidai  It looks ok! :+1:  
DYT that 80% coverage minimal level is a little to big? :

**Comment by milanafinkel** [comment]
Great, thank you!

**Pull request merged**
