### PR TITLE
Adding vulnerability scanner in cloudslang

### LINKED ISSUE #910: [Security] Get notifications about vulnerable third parties at build time
Configure the owasp maven plugin and apply it to the build

### PR DESCRIPTION
**Pull request by lucian-cm**
Fixes #910 
Vulnerability scanner checks for known vulnerabilities in NVD databases for a certain period.
Signed-off-by: Lucian Musca <lucian-cristian.musca@hpe.com>

### CODE REVIEW

**Comment by Bonczidai** [comment]
seems like a cool addition 👍 


while running locally:
```
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.resolution.ArtifactResolutionException
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
	... 60 more

[ERROR] Failed to execute goal org.owasp:dependency-check-maven:1.4.3:check (scan-vulnerabilities-in-used-third-parties) on project cloudslang-spi: Execution scan-vulnerabilities-in-used-third-parties of goal org.owasp:dependency-check-maven:1.4.3:check failed: A required class was missing while executing org.owasp:dependency-check-maven:1.4.3:check: org/eclipse/aether/resolution/ArtifactResolutionException
```

we need to make sure it works seamlessly.. also what is the build time increase with this plugin?

**Comment by lucian-cm** [comment]
Hi @Bonczidai, the issue you are seeing with ClassNotFound is because of the maven version.

**Comment by lucian-cm** [comment]
Moving vulnerability scanner to profile, to not wait 3-4 minutes every build.

**Comment by Bonczidai** [comment]
pending on Jenkins build

**Pull request merged**
