### PR TITLE
Fix the inputs binding event to keep the order of the inputs

### LINKED ISSUE #357: The order of inputs/outputs during binding events is random, and should be as it defined in the flow itself

### PR DESCRIPTION
**Pull request by oritstone**
Fixes #357 

Signed-off-by: Orit Stone <orit.stone@hp.com>

### CODE REVIEW

**Comment by Bonczidai** [comment]
I'd also add tests to verify the inputs / outputs order.. WDYT? @oritstone @meirwah

**Comment by meirwah** [comment]
agree @Bonczidai

**Comment by Bonczidai** [comment]
added tests in `runtime` module.. please review @meirwah

**Comment by meirwah** [comment]
:+1:

**Pull request merged**
