### PR TITLE
validate required inputs

### LINKED ISSUE #224: Required input can be passed as empty
1. Have an operation with an input but no value
2. Run it and do not provide --i
Result: you are required to run it as error appears: 
Command failed java.lang.RuntimeException: Slang Error : Error running: 'fileListParser': Input with name: 'fileList' is Required, but value is empty
3. Provide input with --i but with no actual value

Expected result: just input name and no value should not make the flow continue
Actual result: flow finishes with empty required input!

### PR DESCRIPTION
**Pull request by Bonczidai**
Fixes #224 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hp.com>

### CODE REVIEW

**Comment by Bonczidai** [comment]
the validation cases for required inputs:

- null value
- empty string
- empty collection

**Comment by meirwah** [comment]
:+1:

**Comment by meirwah** [comment]
I think we have an issue here...
Let's look at this op for example : 
https://github.com/CloudSlang/cloud-slang-content/blob/master/content/io/cloudslang/coreos/get_machine_public_ip.sl

Where we have an input of:
- privateKeyFile:
        default: "''"

This is by defualt requiered=true, means it will fail for sure...

We have similar inputs all over our content... so we need to be carful about this PR (maybe wait to have System tests merged? )...

Maybe keep it for now? and fix later ?

**Comment by meirwah** [comment]
Or fix this in all the content...

**Pull request closed without merging**
