### PR TITLE
use spring-io platform third party recommendations and also use latest score

### PR DESCRIPTION
**Pull request by i022098**

### CODE REVIEW

**Comment by orius123** [comment]
Y did U change Jcommander version?

**Comment by i022098** [comment]
yes, i changed it to fit spring-io versions

**Comment by orius123** [comment]
Well. 1.35 was released two years ago. So just make sure there are no important features/bug-fixes that will hurt us.

**Comment by oritstone** [comment]
I went over all their commits since 1.35
It seems that there were no bug fixes, only added 3 new small features that we do not use
@orius123 do you see a problem with this version downgrade?

**Comment by orius123** [comment]
If U went over it than no.

**Pull request merged**
