### PR TITLE
Content format validation

### LINKED ISSUE #944: Content format validation
it would be a nice feature in the content validation of the .sl files to have the following:
- ###########################################################################
  before the YAML start tag
- ###########################################################################
  after the YAML end flag
- One newline between @description @input, @output @result

### PR DESCRIPTION
**Pull request by gituser173**
Fixes #944

Signed-off-by: Claudiu Ban claudiu-laurian.ban@hpe.com

### CODE REVIEW

**Comment by Bonczidai** [comment]
@gituser173 can you please summarize here the design decisions you made and validations you added?

**Comment by Bonczidai** [comment]
also, please sync with @tethryus for validation

**Comment by Bonczidai** [comment]
@lucian-cm please also take a look

**Comment by gituser173** [comment]
@Bonczidai "One newline after each step" was not done, everything else is done

**Pull request merged**
