### PR TITLE
Add Python 'get' function

### LINKED ISSUE #420: Introduce get('key', 'default') function for outputs [1]
Many times when binding outputs the user need to check if a certain key is available in the context and if not bind a default value.
The way it is usually done is by `key' if 'key' in locals() else 'default'`.
I suggest we put a function that does this exact logic in the context when binding outputs,
than the user will be able to simplify his outputs to `get('key', 'default')`

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #420 

Signed-off-by: Bonczidai Levente levente.bonczidai@hpe.com

### CODE REVIEW

**Comment by Bonczidai** [comment]
clarify:

`get('key', 'default_value')` : 

- this Python function can be used in any place where we evaluate a Python expression (outputs, inputs, loop expressions) but not in Python actions
- returns the `value` associated with `key` if the `key` is defined and its `value` is not **null** else `default value`

**Comment by oritstone** [comment]
Nice work :+1: 
Maybe you should also add tests for:
- Using the new get() in operation result evaluation
- Add to the flow an input that uses the actual python locals().get() function to see it still works

Another comment: 
should it be called get() as is the original python action? Maybe we should find another name? WDYT? @Bonczidai @mihaitusa @gituser173 @orius123 @meirwah @avigail-oron

**Comment by orius123** [comment]
I'm fine with the name.

**Comment by orius123** [comment]
What is the performance impact? Cant we declare it once as a static/utility method somehow?

**Comment by Bonczidai** [comment]
@orius123 I wouldn't say the performance impact is notable (it adds 1 ms to each evaluation) 

I've investigated adding it as a utility function, but seems like `ScriptEngine` and `Jython` does not support such a thing.. neither helped the hacking.. main problem is, when the `get` function is evaluated it saves the current context as globals so we cannot save the function as a `PyFunction` for example (doesn't take the values from later script context)

p.s. I am also fine with the name

**Comment by oritstone** [comment]
@SamMarkowitz we need to add it to our docs as well

**Comment by SamMarkowitz** [comment]
Yes, I will add and issue on the docs repo.

**Pull request merged**
