### PR TITLE
Add start task event

### LINKED ISSUE #412: loop for range(1,0) error during navigation
If you try to do loop for `range(1,0)` , you get exception :
```bash
 Caused by: java.lang.RuntimeException: Error evaluating for loop expression in task 'UpdateFile',
	Error is: expression is empty
	at io.cloudslang.lang.runtime.bindings.LoopsBinding.createForLoopCondition(LoopsBinding.java:114)
	at io.cloudslang.lang.runtime.bindings.LoopsBinding.getOrCreateLoopCondition(LoopsBinding.java:52)
	at io.cloudslang.lang.runtime.steps.TaskSteps.beginTask(TaskSteps.java:75)
	... 14 more
2015-08-11 14:45:17,288 [1_WorkerExecutionThread-11_124100057] (ReflectionAdapterImpl.java:72) ERROR - Failed to run the action! Class: io.cloudslang.lang.runtime.navigations.Navigations, method: navigate, reason: Error running: UpdateFile: Error evaluating for loop expression in task 'UpdateFile',
	Error is: expression is empty
```

### PR DESCRIPTION
**Pull request by orius123**
Fixes #412

### CODE REVIEW

**Comment by meirwah** [comment]
@shajyhia  did you review it?

**Comment by orius123** [comment]
@meirwah dont merge all of it to master, the cli part should be in next release

**Comment by meirwah** [comment]
so I can merge all to master?

**Comment by orius123** [comment]
if you reviewed the code go ahead.

**Comment by meirwah** [comment]
please update branch...

**Comment by meirwah** [comment]
tests are failing...

**Pull request merged**
