### PR TITLE
eliminate commons-collections4 dependency. Signed-off-by: dan-alexandru.persa@hpe.com

### LINKED ISSUE #501: Remove Apache commons-collections4-4.0.jar when embedding in OO
When the following dependency is used in OO

```
<dependency>
            <groupId>${cloudslang.groupId}</groupId>
            <artifactId>cloudslang-all</artifactId>
            <version>${cloudslang.version}</version>
        </dependency>
```

as a third party dependency `commons-collection4` version `4.0` is brought, making duplicate classpath entries in Operations Orchestration Central for cloud slang version 0.8.0.1.

### PR DESCRIPTION
**Pull request by Alex-Persa**
Fixes #501

### CODE REVIEW

**Comment by meshipeer** [comment]
fixes #501

**Comment by Bonczidai** [comment]
this one can be closed, right? since it was merged into 0.8

**Comment by Alex-Persa** [comment]
This should be included in master too as HP Operations Orchestrations will be using next releases of this component as well.

**Comment by oritstone** [comment]
We will not merge it to master yet, especially until OO needs to use a newer version

**Comment by orius123** [comment]
Cant slang be embedded as uber jar or something? It's unreasonable that all third parties will have to be same as the embedding app..

**Pull request closed without merging**
