### PR TITLE
fix file name for builder

### LINKED ISSUE #1004: Builder - file name not printed
https://travis-ci.org/CloudSlang/cloud-slang-content/builds/238929220?utm_source=github_status&utm_medium=notification

```console
02/06/17 22:05:30 [INFO] Test case passed: testRemoteSecureCopySucessLocalToRemote [/home/travis/build/CloudSlang/cloud-slang-content/test/io/cloudslang/base/remote_file_transfer/remote_secure_copy.inputs.yaml]. Finished running: io.cloudslang.base.remote_file_transfer.test_remote_secure_copy_local_to_remote with result: SUCCESS
02/06/17 22:05:30 [ERROR]
02/06/17 22:05:30 [ERROR] ------------------------------------------------------------
02/06/17 22:05:30 [ERROR] Exception: Error at line [13] - There should be an empty line between two sections of different tags (@description and @input)
02/06/17 22:05:30 [ERROR] Exception: Error at line [13] - There should be an empty line between two sections of different tags (@description and @input)
02/06/17 22:05:30 [ERROR] Exception: Error at line [11] - There should be an empty line between two sections of different tags (@description and @input)
02/06/17 22:05:30 [ERROR] Exception: Error at line [12] - There should be an empty line between two sections of different tags (@description and @input)
02/06/17 22:05:30 [ERROR] FAILURE: Validation of slang files for project: "/home/travis/build/CloudSlang/cloud-slang-content" failed.
02/06/17 22:05:30 [ERROR] ---------------
```

which file?

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #1004 

Signed-off-by: Bonczidai Levente levente.bonczidai@hpe.com

### CODE REVIEW

**Comment by Bonczidai** [comment]
```console
03:54:37 [ERROR]
03:54:37 [ERROR] ------------------------------------------------------------
03:54:37 [ERROR] Exception: Failed to extract metadata for file: '<content path>\content\io\cloudslang\base\print\print_text.sl'.
Error at line [11] - There should be an empty line between two sections of different tags (@description and @input)
03:54:37 [ERROR] Exception: Failed to extract metadata for file: '<content path>\content\io\cloudslang\base\print\print_text2.sl'.
Error at line [11] - There should be an empty line between two sections of different tags (@description and @input)
03:54:37 [ERROR] Exception: Failed to extract metadata for file: '<content path>\content\io\cloudslang\base\print\print_text2.sl'.
Error at line [12] - There should be an empty line between two sections of different tags (@input and @result)
03:54:37 [ERROR] FAILURE: Validation of slang files for project: "<content path>\" failed.
```

**Comment by Bonczidai** [comment]
also need to add prefix for compilation issue: `exceptions.addAll(preCompileResult.getErrors());`

**Comment by Bonczidai** [comment]
```console
11:26:46 [INFO] Successfully finished Compilation of: 583 Slang files
11:26:46 [ERROR]
11:26:46 [ERROR] ------------------------------------------------------------
11:26:46 [ERROR] Exception: Failed to extract metadata for file: 'C:\Users\bonczida\all\01\workdir\projects\01\cloud-slang-content\content\io\cloudslang\base\datetime\offset_time_by.sl'.
Error at line [21] - There should be an empty line between two sections of different tags (@input and @output)
11:26:46 [ERROR] Exception: Failed to compile file: 'C:\Users\bonczida\all\01\workdir\projects\01\cloud-slang-content\content\io\cloudslang\base\http\http_client_patch.sl'.
For flow 'http_client_patch' syntax is illegal.
key: sensitiveX in input: password is not a known property
11:26:46 [ERROR] Exception: Error validating Slang file: 'C:\Users\bonczida\all\01\workdir\projects\01\cloud-slang-content\content\io\cloudslang\base\json\add_value.sl'. Namespace of slang source: add_value is wrong.
It is currently 'io.cloudslang.json', but it should match the file path: 'C:\Users\bonczida\all\01\workdir\projects\01\cloud-slang-content\content\io\cloudslang\base\json\add_value.sl'
11:26:46 [ERROR] Exception: Some Slang files were not pre-compiled.
Found: 600 executable files in path: 'C:\Users\bonczida\all\01\workdir\projects\01\cloud-slang-content\\content' But managed to create slang models for only: 599
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.openstack.openstack_health_check'.
Failed compiling slang source: io.cloudslang.openstack.utils.create_boot_json. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.openstack.servers.create_server_flow'.
Failed compiling slang source: io.cloudslang.openstack.utils.create_boot_json. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.hashicorp.vault.seal_unseal.unseal_vault_now'.
Failed compiling slang source: io.cloudslang.hashicorp.vault.utils.compute_unseal_body. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.heroku.domains.create_domain'.
Failed compiling slang source: io.cloudslang.heroku.domains.create_domain. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.heroku.account.update_account_email'.
Failed compiling slang source: io.cloudslang.heroku.account.update_account_email. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.hashicorp.vault.seal_unseal.unseal_vault'.
Failed compiling slang source: io.cloudslang.hashicorp.vault.utils.compute_unseal_body. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.heroku.account.update_account_password'.
Failed compiling slang source: io.cloudslang.heroku.account.update_account_password. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.openstack.utils.create_boot_json'.
Failed compiling slang source: io.cloudslang.openstack.utils.create_boot_json. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.haven_on_demand.examples.video_text_search.build_index_item'.
Failed compiling slang source: io.cloudslang.haven_on_demand.examples.video_text_search.build_index_item. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.heroku.account.update_account'.
Failed compiling slang source: io.cloudslang.heroku.account.update_account. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.new_relic.servers.update_server_name'.
Failed compiling slang source: io.cloudslang.new_relic.servers.update_server_name. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.hashicorp.vault.utils.compute_unseal_body'.
Failed compiling slang source: io.cloudslang.hashicorp.vault.utils.compute_unseal_body. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.heroku.collaborators.create_application_collaborator'.
Failed compiling slang source: io.cloudslang.heroku.collaborators.create_application_collaborator. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.haven_on_demand.examples.video_text_search.add_to_index'.
Failed compiling slang source: io.cloudslang.haven_on_demand.examples.video_text_search.build_index_item. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.haven_on_demand.examples.video_text_search.setup_index'.
Failed compiling slang source: io.cloudslang.haven_on_demand.examples.video_text_search.build_index_item. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Failed compiling Slang source: 'io.cloudslang.heroku.applications.create_application'.
Failed compiling slang source: io.cloudslang.heroku.applications.create_application. Missing dependency: io.cloudslang.base.json.add_value
11:26:46 [ERROR] Exception: Some Slang files were not compiled.
Found: 599 slang models, but managed to compile only: 583
11:26:46 [ERROR] FAILURE: Validation of slang files for project: "C:\Users\bonczida\all\01\workdir\projects\01\cloud-slang-content\" failed.
11:26:46 [ERROR] ------------------------------------------------------------
11:26:46 [ERROR]
```

**Comment by Bonczidai** [comment]
11:26:46 [ERROR] Exception: **Failed to extract metadata for file**: '<content path>\content\io\cloudslang\base\datetime\offset_time_by.sl'.
Error at line [21] - There should be an empty line between two sections of different tags (`@input` and `@output`)
11:26:46 [ERROR] Exception: **Failed to compile file**: '<content path>\content\io\cloudslang\base\http\http_client_patch.sl'.
For flow 'http_client_patch' syntax is illegal.
key: sensitiveX in input: password is not a known property
11:26:46 [ERROR] Exception: Error validating Slang file: '<content path>\content\io\cloudslang\base\json\add_value.sl'. Namespace of slang source: add_value is wrong.
It is currently 'io.cloudslang.json', but it should match the file path: '<content path>\content\io\cloudslang\base\json\add_value.sl'
11:26:46 [ERROR] Exception: Some Slang files were not pre-compiled.

**Comment by Bonczidai** [comment]
adding @andreivasiletruta @CimpeanRadu

**Comment by andreivasiletruta** [comment]
@Bonczidai looks really nice based on the snipped above.

**Comment by Bonczidai** [comment]
@tethryus did you have a chance to take a look?

**Pull request merged**
