### PR TITLE
Add to cli verbose flag with verbosity levels

### LINKED ISSUE #484: Add to cli "--verbose" flag with verbosity levels
Merge "--debug" and "--quiet" flag to " --verbose" flag with option to choose verbosity level.
Verbosity levels:
1. default
2. quiet
3. debug

### PR DESCRIPTION
**Pull request by gituser173**
Fixes #484 
Signed-off-by: Claudiu Ban claudiu-laurian.ban@hpe.com

### CODE REVIEW

**Comment by gituser173** [comment]
@maayan-avraham please review

**Comment by maayan-avraham** [comment]
@gituser173 :+1:

**Comment by gituser173** [comment]
@maayan-avraham WDYT?

**Comment by maayan-avraham** [comment]
@gituser173  I think it's good! when I run --v with illegal string I get the default level. maybe it's should behave like --v without any string (debug level) , WDYT?

**Comment by gituser173** [comment]
currently when you run --v without arguments or illegal string you get debug level, when you run a command without --v entirely you get default level

let me know if and how I should change this

**Comment by maayan-avraham** [comment]
@gituser173 I just tested it-> when I run with "--v someIllegalString" I get the default level, and not the debug level like you said

**Comment by gituser173** [comment]
yes I was wrong, what should we get for "--v someIllegalString"?

**Comment by Bonczidai** [comment]
IMHO `--v illegalString` should fire an error

**Comment by maayan-avraham** [comment]
@gituser173  :ok_hand:

**Pull request merged**
