### PR TITLE
Support flow description

### LINKED ISSUE #505: support flow description

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #505 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

**Comment by Bonczidai** [comment]
currently:

- support for flow description
- support for operation description
- CLI inspect cmd: print path, namespace, name, description of executable

this PR is ready for review - not ready for merge!

**Comment by Bonczidai** [comment]
please give feedback @CloudSlang/slang-functional-reviewers

**Comment by gituser173** [comment]
@oritstone 
Implementation proposal: 
MetadataParser/MetadataExtractor interface with one "parseMetadata"/"extractMetadata"(whichever you prefer) method that takes a SlangSource parameter and returns a Metadata pojo containing all the description items, and of course MetadataParserImpl/MetadataExtractorImpl, all this done inside the cloudslang-compiler. This will be separated from the SlangCompiler interface and it's "compile" and "preCompile" methods. Let me know which name you prefer.

**Comment by Bonczidai** [comment]
moved to another PR

**Pull request closed without merging**
