### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by meirwah**
fix website links

### CODE REVIEW

**Comment by meirwah** [comment]
@SamMarkowitz  look at this...

**Comment by SamMarkowitz** [comment]
Yes, this is the one with the npm that we were waiting on. 

We need to also change the rest of the file: the header, everywhere it says just Slang, and the CLI folder and executable names.

**Comment by SamMarkowitz** [comment]
Do you want me to merge your changes and do the rest myself?

**Comment by meirwah** [comment]
yes

**Pull request merged**
