### PR TITLE
Add extensions keyword

### LINKED ISSUE #643: add extension `extentions` tag that can be ignored

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #643

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

**Comment by orius123** [comment]
what is extensions?

**Comment by Bonczidai** [comment]
top level keyword in .sl files to be ignored by the compiler -- you can e.g. put graphical data under it

**Comment by orius123** [comment]
like in `Java` and `python` that you can put un-related data inside the language files?
```java
class Car {
private int wheels = 4
...
extensions:
  - need to fix my car
  - The common goldfish can live for over 20 years...
}
```
got it right?

**Comment by orius123** [comment]
Maybe that was a bit sarcastic.. 
I think it's a **completely wrong** idea to put data  that in not cloudslang in cloudslang files, after all that is why they are called cloudlslang files.

**Comment by orius123** [comment]
@CloudSlang/slang-functional-reviewers  WDYT?

**Comment by orius123** [comment]
and some specific mentions @meshipeer @oritstone @tomershadi @ziso

**Pull request merged**
