### PR TITLE
renaming

### LINKED ISSUE #32: score-lang-api name is wrong
it should be score-lang-all  .. or something else since it is not API it is package...

### PR DESCRIPTION
**Pull request by Bonczidai**
Fixes #32
commit nr. 1: rename openscore to cloudslang in package names - handle java and dependent files

Signed-off-by: Bonczidai Levente <levente.bonczidai@hp.com>

### CODE REVIEW

**Comment by Bonczidai** [comment]
commit nr. 2: update build_content folder according to the new repository link and CloudSlang/cloud-slang-content#76

ps. once the all the updates are done the author of these flows should recheck them since there are a lot of things that can go wrong there

**Comment by Bonczidai** [comment]
adding @meshipeer @oritstone @orius123

**Comment by meshipeer** [comment]
solves #32

**Comment by Bonczidai** [comment]
ready for review

**Comment by meshipeer** [comment]
the files didn't keep the History...
please talk to @oritstone
please assign to me to review when finishes

**Comment by oritstone** [comment]
We have the history in GitHub
I'm going to merge it now
@Bonczidai you still need to update all the comments & Java docs

**Pull request merged**
